version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:5000"  # Bind to all interfaces
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ["python", "app.py"]

  signaling-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5001:5001"  # Bind to all interfaces
    environment:
      - PORT=5001
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ["python", "signaling_server.py"]